### ISSUE TITLE
_pickle.PicklingError: Can't pickle X: it's not the same object as __main__.X

### ISSUE THREAD

**Issue by KeyWeeUsr** [kislyuk/ensure#29]
This sample code causes `pickle` to throw an error with multiprocessing. It doesn't matter how many processes. It's due to [this](https://stackoverflow.com/q/9336646/5994041).

```python
from os import getpid
from multiprocessing import Pool
from ensure import ensure_annotations


@ensure_annotations
def test_func(arg):
    print(f'Hello {arg} from {getpid()}!')


if __name__ == '__main__':
    with Pool(processes=1) as pool:
        pool.map(test_func, ['map'])
```

Output:
```python
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    pool.map(test_func, ['map'])
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function test_func at 0x7fd8df8101e0>: it's not the same object as __main__.test_func
```

**Comment by kislyuk** [comment]
Thanks for reporting - it's not clear that this library will be able to do anything about this. There are a few descriptions of workarounds in the thread that you linked.

**Comment by KeyWeeUsr** [comment]
Yeah, I'm also not quite sure how to handle it. It'd be nice to have it somehow even with MP, however perhaps for now at least document it.
